---
# tasks file for tomcat
- name: ensure group exists
  group:
    name: "{{ item.group }}"
  with_items:
    - "{{ tomcat_layout }}"

- name: ensure user exists
  user:
    name: "{{ item.user }}"
    createhome: no
    system: yes
  with_items:
    - "{{ tomcat_layout }}"

- name: ensure tomcat_directory exists
  file:
    path: "{{ item.directory }}"
    state: directory
  with_items:
    - "{{ tomcat_layout }}"

- name: copy tomcat
  copy:
    src: "files/{{ tomcat_archive[item.version]['targz'] }}"
    dest: "{{ item.directory }}"
  with_items:
    - "{{ tomcat_layout }}"

- name: install tomcat
  unarchive:
    src: "{{ item.directory }}/{{ tomcat_archive[item.version]['targz'] }}"
    dest: "{{ item.directory }}"
    group: "{{ item.group }}"
    owner: "{{ item.user }}"
    remote_src: yes
    creates: "{{ item.directory }}/{{ tomcat_archive[item.version]['dir'] }}"
  with_items:
    - "{{ tomcat_layout }}"

- name: configure tomcat
  template:
    src: templates/server.xml.j2
    dest: "{{ item.directory }}/{{ tomcat_archive[item.version]['dir'] }}/conf/server.xml"
  with_items:
    - "{{ tomcat_layout }}"

- name: deploy war files
  copy:
    src: "files/{{ item }}"
    dest: "{{ item.directory }}/{{ tomcat_archive[item.version]['dir'] }}/webapps/"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
  when:
    - tomcat_layout.wars is defined
  with_subelements:
    - "{{ tomcat_layout }}"
    - wars

- name: register tomcat to a sysvinit system
  template:
    src: templates/tomcat.j2
    dest: "/etc/init.d/{{ item.name }}"
    mode: 0750
  when:
    - ansible_service_mgr == "sysvinit" or ansible_service_mgr == "upstart"
  with_items:
    - "{{ tomcat_layout }}"

- name: register tomcat to a systemd system
  template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/{{ item.name }}.service
  when:
    - ansible_service_mgr == "systemd"
  with_items:
    - "{{ tomcat_layout }}"

- name: start and enable software
  service:
    name: "{{ item.name }}"
    state: started
    enabled: yes
  with_items:
    - "{{ tomcat_layout }}"
  when:
    - ansible_virtualization_type != "docker"
