---
# tasks file for tomcat
- name: ensure tomcat_group exists
  group:
    name: "{{ tomcat_group }}"

- name: ensure tomcat_user exists
  user:
    name: "{{ tomcat_user }}"

- name: ensure tomcat_directory exists
  file:
    path: "{{ tomcat_directory }}"
    state: directory

- name: install tomcat
  unarchive:
    src: "{{ tomcat_archive[tomcat_version]['targz'] }}"
    dest: "{{ tomcat_directory }}"
    remote_src: yes
    group: "{{ tomcat_group }}"
    owner: "{{ tomcat_user }}"
    creates: "{{ tomcat_directory }}/{{ tomcat_archive[tomcat_version]['dir'] }}"

- name: configure tomcat
  template:
    src: templates/server.xml.j2
    dest: "{{ tomcat_directory }}/{{ tomcat_archive[tomcat_version]['dir'] }}/conf/server.xml"
  notify: restart software

- name: deploy application
  get_url:
    url: "{{ tomcat_war_url }}"
    dest: "{{ tomcat_directory }}/{{ tomcat_archive[tomcat_version]['dir'] }}/webapps/"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  when:
    - tomcat_war_url is defined

- name: start tomcat
  command: "{{ tomcat_directory }}/{{ tomcat_archive[tomcat_version]['dir'] }}/bin/startup.sh"
  args:
    creates: "{{ tomcat_directory }}/{{ tomcat_archive[tomcat_version]['dir'] }}/temp/tomcat.pid"
  become: yes
  become_user: "{{ tomcat_user }}"
  environment:
    CATALINA_PID: "{{ tomcat_directory }}/{{ tomcat_archive[tomcat_version]['dir'] }}/temp/tomcat.pid"
    USE_NOHUP: true
