---
- name: show shit
  debug:
    var: url

- name: install war
  get_url:
    url: "{{ url }}"
    dest: "{{ item.directory | default(tomcat_directory) }}/{{ tomcat_archive[item.version | default (tomcat_version)]['dir'] }}/webapps/"
