---
- name: show shit
  debug:
    var: tomcat_wars

- name: install war
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.directory | default(tomcat_directory) }}/{{ tomcat_archive[item.version | default (tomcat_version)]['dir'] }}/webapps/"
  with_items: "{{ tomcat_wars }}"
