---
- name: show tomcat_wars all
  debug:
    var: tomcat_wars

- name: show tomcat_wars url
  debug:
    msg: "{{ item }}"
  with_items: "{{ tomcat_wars.url }}"

- name: loop over tomcat_wars
  get_url:
    url: "{{ item }}"
    dest: "{{ item.directory | default(tomcat_directory) }}/{{ tomcat_archive[item.version | default (tomcat_version)]['dir'] }}/webapps/"
  with_items: "{{ tomcat_wars.url }}"
  when:
    - item is defined
