---
- name: show tomcat_wars
  debug:
    msg: "{{ item.url }}"
  with_items: "{{ tomcat_wars }}"
  when:
    - tomcat_wars.url is defined

- name: loop over tomcat_wars
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.directory | default(tomcat_directory) }}/{{ tomcat_archive[item.version | default (tomcat_version)]['dir'] }}/webapps/"
  with_items: "{{ tomcat_wars }}"
  when:
    - tomcat_wars.url is defined
